system:
  port: 8889
  successCode: 1
  successMessage: Success
  errorCode: 0
  errorMessage: Failed

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  database: szzn_admin

sqlite:
  path: ./cook.db

commandRPC:
  host: localhost
  port: 50051